// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AlertInitParameters struct {

	// (Boolean) Whether the alert is active (defaults to true on creation).
	// Whether the alert is active (defaults to true on creation).
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// References to Channel in channel to populate channelIds.
	// +kubebuilder:validation:Optional
	ChannelIDRefs []v1.NamespacedReference `json:"channelIdRefs,omitempty" tf:"-"`

	// Selector for a list of Channel in channel to populate channelIds.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`

	// (Set of String) Set of channel IDs to notify.
	// Set of channel IDs to notify.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/namespaced/channel/v1alpha1.Channel
	// +crossplane:generate:reference:refFieldName=ChannelIDRefs
	// +crossplane:generate:reference:selectorFieldName=ChannelIDSelector
	// +listType=set
	ChannelIds []*string `json:"channelIds,omitempty" tf:"channel_ids,omitempty"`

	// (String) Alert description.
	// Alert description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Evaluation frequency as Go duration.
	// Evaluation frequency as Go duration.
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (String) Alert name (unique per project).
	// Alert name (unique per project).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Notification rule. Must match API enum.
	// Notification rule. Must match API enum.
	NotifyWhen *string `json:"notifyWhen,omitempty" tf:"notify_when,omitempty"`

	// (String) Project ID (UUID) used for alert API paths.
	// Project ID (UUID) used for alert API paths.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/namespaced/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) SQL / query string used by the alert.
	// SQL / query string used by the alert.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`

	// (String) Lookback window as Go duration.
	// Lookback window as Go duration.
	TimeWindow *string `json:"timeWindow,omitempty" tf:"time_window,omitempty"`
}

type AlertObservation struct {

	// (Boolean) Whether the alert is active (defaults to true on creation).
	// Whether the alert is active (defaults to true on creation).
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Set of String) Set of channel IDs to notify.
	// Set of channel IDs to notify.
	// +listType=set
	ChannelIds []*string `json:"channelIds,omitempty" tf:"channel_ids,omitempty"`

	// (String) Alert description.
	// Alert description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Evaluation frequency as Go duration.
	// Evaluation frequency as Go duration.
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (String) Alert ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Alert name (unique per project).
	// Alert name (unique per project).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Notification rule. Must match API enum.
	// Notification rule. Must match API enum.
	NotifyWhen *string `json:"notifyWhen,omitempty" tf:"notify_when,omitempty"`

	// (String) Project ID (UUID) used for alert API paths.
	// Project ID (UUID) used for alert API paths.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) SQL / query string used by the alert.
	// SQL / query string used by the alert.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`

	// (String) Lookback window as Go duration.
	// Lookback window as Go duration.
	TimeWindow *string `json:"timeWindow,omitempty" tf:"time_window,omitempty"`

	// managed watermark (lateness tolerance) sent to the API.
	// Provider-managed watermark (lateness tolerance) sent to the API.
	Watermark *string `json:"watermark,omitempty" tf:"watermark,omitempty"`
}

type AlertParameters struct {

	// (Boolean) Whether the alert is active (defaults to true on creation).
	// Whether the alert is active (defaults to true on creation).
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// References to Channel in channel to populate channelIds.
	// +kubebuilder:validation:Optional
	ChannelIDRefs []v1.NamespacedReference `json:"channelIdRefs,omitempty" tf:"-"`

	// Selector for a list of Channel in channel to populate channelIds.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`

	// (Set of String) Set of channel IDs to notify.
	// Set of channel IDs to notify.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/namespaced/channel/v1alpha1.Channel
	// +crossplane:generate:reference:refFieldName=ChannelIDRefs
	// +crossplane:generate:reference:selectorFieldName=ChannelIDSelector
	// +kubebuilder:validation:Optional
	// +listType=set
	ChannelIds []*string `json:"channelIds,omitempty" tf:"channel_ids,omitempty"`

	// (String) Alert description.
	// Alert description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Evaluation frequency as Go duration.
	// Evaluation frequency as Go duration.
	// +kubebuilder:validation:Optional
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (String) Alert name (unique per project).
	// Alert name (unique per project).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Notification rule. Must match API enum.
	// Notification rule. Must match API enum.
	// +kubebuilder:validation:Optional
	NotifyWhen *string `json:"notifyWhen,omitempty" tf:"notify_when,omitempty"`

	// (String) Project ID (UUID) used for alert API paths.
	// Project ID (UUID) used for alert API paths.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) SQL / query string used by the alert.
	// SQL / query string used by the alert.
	// +kubebuilder:validation:Optional
	Query *string `json:"query,omitempty" tf:"query,omitempty"`

	// (String) Lookback window as Go duration.
	// Lookback window as Go duration.
	// +kubebuilder:validation:Optional
	TimeWindow *string `json:"timeWindow,omitempty" tf:"time_window,omitempty"`
}

// AlertSpec defines the desired state of Alert
type AlertSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AlertParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AlertInitParameters `json:"initProvider,omitempty"`
}

// AlertStatus defines the observed state of Alert.
type AlertStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AlertObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Alert is the Schema for the Alerts API. Manages a Logfire alert.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,logfire}
type Alert struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.frequency) || (has(self.initProvider) && has(self.initProvider.frequency))",message="spec.forProvider.frequency is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.notifyWhen) || (has(self.initProvider) && has(self.initProvider.notifyWhen))",message="spec.forProvider.notifyWhen is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.query) || (has(self.initProvider) && has(self.initProvider.query))",message="spec.forProvider.query is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.timeWindow) || (has(self.initProvider) && has(self.initProvider.timeWindow))",message="spec.forProvider.timeWindow is a required parameter"
	Spec   AlertSpec   `json:"spec"`
	Status AlertStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AlertList contains a list of Alerts
type AlertList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Alert `json:"items"`
}

// Repository type metadata.
var (
	Alert_Kind             = "Alert"
	Alert_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Alert_Kind}.String()
	Alert_KindAPIVersion   = Alert_Kind + "." + CRDGroupVersion.String()
	Alert_GroupVersionKind = CRDGroupVersion.WithKind(Alert_Kind)
)

func init() {
	SchemeBuilder.Register(&Alert{}, &AlertList{})
}
