// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/pydantic/provider-upjet-logfire/apis/namespaced/channel/v1alpha1"
	v1alpha11 "github.com/pydantic/provider-upjet-logfire/apis/namespaced/project/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Alert.
func (mg *Alert) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ChannelIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ChannelIDRefs,
		Selector:      mg.Spec.ForProvider.ChannelIDSelector,
		To: reference.To{
			List:    &v1alpha1.ChannelList{},
			Managed: &v1alpha1.Channel{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ChannelIds")
	}
	mg.Spec.ForProvider.ChannelIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ChannelIDRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &v1alpha11.ProjectList{},
			Managed: &v1alpha11.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.ChannelIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ChannelIDRefs,
		Selector:      mg.Spec.InitProvider.ChannelIDSelector,
		To: reference.To{
			List:    &v1alpha1.ChannelList{},
			Managed: &v1alpha1.Channel{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ChannelIds")
	}
	mg.Spec.InitProvider.ChannelIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ChannelIDRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &v1alpha11.ProjectList{},
			Managed: &v1alpha11.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}
