// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type WriteTokenInitParameters struct {

	// 12-31T23:59:59Z). If omitted, the token does not expire.
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) UUID of the project that owns the token.
	// UUID of the project that owns the token.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/cluster/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

type WriteTokenObservation struct {

	// (String) Timestamp when the token was created.
	// Timestamp when the token was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Display name of the user that created the token.
	// Display name of the user that created the token.
	CreatedByName *string `json:"createdByName,omitempty" tf:"created_by_name,omitempty"`

	// managed tokens.
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// 12-31T23:59:59Z). If omitted, the token does not expire.
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) Write token identifier.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) UUID of the project that owns the token.
	// UUID of the project that owns the token.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) Name of the project that owns the token.
	// Name of the project that owns the token.
	ProjectName *string `json:"projectName,omitempty" tf:"project_name,omitempty"`

	// (String) Prefix of the generated write token.
	// Prefix of the generated write token.
	TokenPrefix *string `json:"tokenPrefix,omitempty" tf:"token_prefix,omitempty"`
}

type WriteTokenParameters struct {

	// 12-31T23:59:59Z). If omitted, the token does not expire.
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	// +kubebuilder:validation:Optional
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) UUID of the project that owns the token.
	// UUID of the project that owns the token.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

// WriteTokenSpec defines the desired state of WriteToken
type WriteTokenSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WriteTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WriteTokenInitParameters `json:"initProvider,omitempty"`
}

// WriteTokenStatus defines the observed state of WriteToken.
type WriteTokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WriteTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WriteToken is the Schema for the WriteTokens API. Manages a Logfire write token.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,logfire}
type WriteToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WriteTokenSpec   `json:"spec"`
	Status            WriteTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WriteTokenList contains a list of WriteTokens
type WriteTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WriteToken `json:"items"`
}

// Repository type metadata.
var (
	WriteToken_Kind             = "WriteToken"
	WriteToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WriteToken_Kind}.String()
	WriteToken_KindAPIVersion   = WriteToken_Kind + "." + CRDGroupVersion.String()
	WriteToken_GroupVersionKind = CRDGroupVersion.WithKind(WriteToken_Kind)
)

func init() {
	SchemeBuilder.Register(&WriteToken{}, &WriteTokenList{})
}
