// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ReadTokenInitParameters struct {

	// 12-31T23:59:59Z). If omitted, the token does not expire.
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) UUID of the project that owns the token.
	// UUID of the project that owns the token.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/namespaced/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`
}

type ReadTokenObservation struct {

	// (String) Timestamp when the token was created.
	// Timestamp when the token was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Display name of the user that created the token.
	// Display name of the user that created the token.
	CreatedByName *string `json:"createdByName,omitempty" tf:"created_by_name,omitempty"`

	// managed tokens.
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// 12-31T23:59:59Z). If omitted, the token does not expire.
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) Read token identifier.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) UUID of the project that owns the token.
	// UUID of the project that owns the token.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) Name of the project that owns the token.
	// Name of the project that owns the token.
	ProjectName *string `json:"projectName,omitempty" tf:"project_name,omitempty"`

	// (String) Prefix of the generated read token.
	// Prefix of the generated read token.
	TokenPrefix *string `json:"tokenPrefix,omitempty" tf:"token_prefix,omitempty"`
}

type ReadTokenParameters struct {

	// 12-31T23:59:59Z). If omitted, the token does not expire.
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	// +kubebuilder:validation:Optional
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) UUID of the project that owns the token.
	// UUID of the project that owns the token.
	// +crossplane:generate:reference:type=github.com/pydantic/provider-upjet-logfire/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`
}

// ReadTokenSpec defines the desired state of ReadToken
type ReadTokenSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ReadTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReadTokenInitParameters `json:"initProvider,omitempty"`
}

// ReadTokenStatus defines the observed state of ReadToken.
type ReadTokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ReadTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReadToken is the Schema for the ReadTokens API. Manages a Logfire read token.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,logfire}
type ReadToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReadTokenSpec   `json:"spec"`
	Status            ReadTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReadTokenList contains a list of ReadTokens
type ReadTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReadToken `json:"items"`
}

// Repository type metadata.
var (
	ReadToken_Kind             = "ReadToken"
	ReadToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReadToken_Kind}.String()
	ReadToken_KindAPIVersion   = ReadToken_Kind + "." + CRDGroupVersion.String()
	ReadToken_GroupVersionKind = CRDGroupVersion.WithKind(ReadToken_Kind)
)

func init() {
	SchemeBuilder.Register(&ReadToken{}, &ReadTokenList{})
}
