// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ChannelInitParameters struct {

	// (Boolean) Whether the channel is active.
	// Whether the channel is active.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Block, Optional) Required channel configuration. (see below for nested schema)
	// Required channel configuration.
	Config *ConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Channel name.
	// Channel name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ChannelObservation struct {

	// (Boolean) Whether the channel is active.
	// Whether the channel is active.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Block, Optional) Required channel configuration. (see below for nested schema)
	// Required channel configuration.
	Config *ConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Channel ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Channel name.
	// Channel name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ChannelParameters struct {

	// (Boolean) Whether the channel is active.
	// Whether the channel is active.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Block, Optional) Required channel configuration. (see below for nested schema)
	// Required channel configuration.
	// +kubebuilder:validation:Optional
	Config *ConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Channel name.
	// Channel name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ConfigInitParameters struct {

	// (String, Sensitive) Opsgenie API key.
	// Opsgenie API key.
	AuthKeySecretRef *v1.SecretKeySelector `json:"authKeySecretRef,omitempty" tf:"-"`

	// (String) Webhook payload format.
	// Webhook payload format.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Channel type (webhook or opsgenie).
	// Channel type (`webhook` or `opsgenie`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Webhook URL endpoint.
	// Webhook URL endpoint.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ConfigObservation struct {

	// (String) Webhook payload format.
	// Webhook payload format.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Channel type (webhook or opsgenie).
	// Channel type (`webhook` or `opsgenie`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Webhook URL endpoint.
	// Webhook URL endpoint.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ConfigParameters struct {

	// (String, Sensitive) Opsgenie API key.
	// Opsgenie API key.
	// +kubebuilder:validation:Optional
	AuthKeySecretRef *v1.SecretKeySelector `json:"authKeySecretRef,omitempty" tf:"-"`

	// (String) Webhook payload format.
	// Webhook payload format.
	// +kubebuilder:validation:Optional
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Channel type (webhook or opsgenie).
	// Channel type (`webhook` or `opsgenie`).
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// (String) Webhook URL endpoint.
	// Webhook URL endpoint.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// ChannelSpec defines the desired state of Channel
type ChannelSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ChannelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ChannelInitParameters `json:"initProvider,omitempty"`
}

// ChannelStatus defines the observed state of Channel.
type ChannelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ChannelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Channel is the Schema for the Channels API. Manages a Logfire alert channel.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,logfire}
type Channel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.config) || (has(self.initProvider) && has(self.initProvider.config))",message="spec.forProvider.config is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ChannelSpec   `json:"spec"`
	Status ChannelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ChannelList contains a list of Channels
type ChannelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Channel `json:"items"`
}

// Repository type metadata.
var (
	Channel_Kind             = "Channel"
	Channel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Channel_Kind}.String()
	Channel_KindAPIVersion   = Channel_Kind + "." + CRDGroupVersion.String()
	Channel_GroupVersionKind = CRDGroupVersion.WithKind(Channel_Kind)
)

func init() {
	SchemeBuilder.Register(&Channel{}, &ChannelList{})
}
